insert into regions (id, label)
values (1, 'Mondstadt'),
       (2, 'Liyue'),
       (3, 'Inazuma');

insert into ascensions (level, stone, rarity_stone, core, flower, item, rarity_item, moras, xp1, xp2, xp3)
values ('20+', 1, 2, 0, 3, 3, 1, 20000, 1, 0, 6),
       ('40+', 3, 3, 2, 10, 15, 1, 40000, 4, 3, 28),
       ('50+', 6, 3, 4, 20, 12, 2, 60000, 0, 4, 28),
       ('60+', 3, 4, 8, 30, 18, 2, 80000, 0, 3, 42),
       ('70+', 6, 4, 12, 45, 12, 3, 100000, 1, 3, 59),
       ('80+', 6, 5, 20, 60, 24, 3, 120000, 2, 2, 80),
       ('90', 0, 0, 0, 0, 0, 0, 0, 4, 0, 171);

insert into talents (label, core, book, rarity_book, item, rarity_item, moras, crown)
values ('2', 0, 3, 2, 6, 1, 12500, 0),
       ('3', 0, 2, 3, 3, 2, 17500, 0),
       ('4', 0, 4, 3, 4, 2, 25000, 0),
       ('5', 0, 6, 3, 6, 2, 30000, 0),
       ('6', 0, 9, 3, 9, 2, 37500, 0),
       ('7', 1, 4, 4, 4, 3, 120000, 0),
       ('8', 1, 6, 4, 6, 3, 260000, 0),
       ('9', 2, 12, 4, 9, 3, 450000, 0),
       ('10', 2, 16, 4, 12, 3, 700000, 1);

insert into user (uid, pseudo, mail, pass, admin)
    value ('704888866', 'Raiwtsu', 'orgevalthomas@gmail.com',
           '$2y$10$3ncvKqst/S4s4WVLqEPwN.sjYgXZ0lC..Ozy8BuzgbGVmxlIY6aKq', 1);

insert into items (type, label, rarity, item_lower, effect, description, region)
values ('Character EXP', 'Wanderer''s Advice', 2, null, 'Character EXP material. Gives 1000 EXP.',
        'These experiences are still beneficial even if one does not live in Teyvat.', null),
       ('Character EXP', 'Adventurer''s Experience', 3, 1, 'Character EXP material. Gives 5,000 EXP.',
        'These experiences are very beneficial for journeys into the unknown.', null),
       ('Character EXP', 'Hero''s Wit', 4, 2, 'Character EXP material. Gives 20,000 EXP.',
        'These experiences are extremely precious for a pilgrim traveling through Teyvat in order to be closer to Celestia.',
        null),
       ('Common Ascension', 'Slime Condensate', 1, null, null,
        'A thick coating found on slimes. Most commonly seen material in elemental workshops.', null),
       ('Common Ascension', 'Slime Secretions', 2, 4, null,
        'Mildly purified slime secretions. Harmful to the skin. Please avoid direct exposure.', null),
       ('Common Ascension', 'Slime Concentrate', 3, 5, null,
        'Concentrated slime essence. When left on its own, it will begin to move on its own.', null),
       ('Common Ascension', 'Damaged Mask', 1, null, null,
        'A broken bone mask that once belonged to some hilichurl.
Now more broken than complete, it can no longer perform its primary function.', null),
       ('Common Ascension', 'Stained Mask', 2, 7, null,
        'A bone mask covered in unidentifiable stains and a mysterious odor.
Yet such is the devotion of hilichurls to masks that they will wear it nonetheless.', null),
       ('Common Ascension', 'Ominous Mask', 3, 8, null,
        'A glossy bone mask with oil markings painted on it, meant to intimidate enemies.
No-one really knows why hilichurls are so fascinated with masks. Some say it''s because they don''t want to see their own reflections in the water.',
        null),
       ('Common Ascension', 'Divining Scroll', 1, null, null,
        'A scroll that likely relates to some kind of magic. Exudes an inexplicable but ominous warmth.', null),
       ('Common Ascension', 'Sealed Scroll', 2, 10, null,
        'An old scroll lacking in detail and clarity. By following the images on it, some magical creatures can recreate a small part of its magic.',
        null),
       ('Common Ascension', 'Forbidden Curse Scroll', 3, 11, null,
        'A scroll inscribed with ancient images. It is said that few can decipher its meaning, and the few scholars that have all went mad.',
        null),
       ('Common Ascension', 'Firm Arrowhead', 1, null, null,
        'A roughly produced arrowhead. Though unimpressive, neither it nor the bow should be underestimated, for even the bravest knight can be felled by an arrow from the rear.',
        null),
       ('Common Ascension', 'Sharp Arrowhead', 2, 13, null,
        'A well-made arrowhead. Sharp enough to penetrate armor with the ease of a rock through the surface of water.',
        null),
       ('Common Ascension', 'Weathered Arrowhead', 3, 14, null,
        'An old arrowhead coated in blood. The arrowhead has long since lost its sharpness and thus its use as a weapon.
However it represents the pride of a hunter and acts as both an amulet and a medal.', null),
       ('Common Ascension', 'Heavy Horn', 2, null, null,
        'A crude horn used by hilichurls to warn each other. Given the damage to the horn, it won''t be warning anyone any time soon.',
        null),
       ('Common Ascension', 'Black Bronze Horn', 3, 16, null,
        'A metallic monster horn that can only be obtained from especially strong hilichurls, since blowing on the horn takes real strength.',
        null),
       ('Common Ascension', 'Black Crystal Horn', 4, 17, null,
        'A metallic horn with an ominous shine decorated with black crystals of an unknown source. It has hardly been used at all. It is likely a ceremonial item of the hilichurls''.',
        null),
       ('Common Ascension', 'Dead Ley Line Branch', 2, null, null,
        'Fragile branches from deep within the earth. Even after years of age, from beneath it''s mottled surface you can see that its power is not yet entirely lost.',
        null),
       ('Common Ascension', 'Dead Ley Line Leaves', 3, 19, null,
        'A twig from deep within the earth. Though it is far from where it once lay, its leaves still pulsate with energy.',
        null),
       ('Common Ascension', 'Ley Line Sprout', 4, 20, null,
        'It is said that there was a great tree whose roots once spread out to every corner of the world, and this branch is said to be part of it. It is almost if it was never broken off and taken far away, for its vitality is such that it still sprouts new leaves even now.',
        null),
       ('Common Ascension', 'Chaos Device', 2, null, null,
        'Comes from ancient defunct relic structures. A part that once held the structure together. Its aesthetically-pleasing engineering is quite exquisite.',
        null),
       ('Common Ascension', 'Chaos Circuit', 3, 22, null,
        'Comes from ancient defunct relic structures. Was once a logic circuit responsible for movement functions. Sadly, no-one is able to make sense of how it worked.',
        null),
       ('Common Ascension', 'Chaos Core', 4, 23, null,
        'Comes from ancient defunct relic structures. The core that once drove a mechanical beast. Should you come to understand its workings and reproduce it, you could perhaps change the world.',
        null),
       ('Common Ascension', 'Mist Grass Pollen', 2, null, null,
        'Strange spores created by Mist Grass in enclosed spaces. They are the Cicins'' favorite food.', null),
       ('Common Ascension', 'Mist Grass', 3, 25, null,
        'Well-preserved Mist Grass. Some would take advantage of the Cicins'' love for the Mist Grass to control them.',
        null),
       ('Common Ascension', 'Mist Grass Wick', 4, 26, null,
        'A rare bundle of Mist Grass that gives off a faint glow. Those who carry it invite both the Cicins and misfortune.',
        null),
       ('Common Ascension', 'Hunter''s Sacrificial Knife', 2, null, null,
        'A sharp alloy weapon. Though its owner has been lost, it still reflects a disturbingly cold light.', null),
       ('Common Ascension', 'Agent''s Sacrificial Knife', 3, 28, null,
        'An oddly-shaped weapon made with superior Snezhnayan technology that once belonged to a senior agent. Proper training is required for using this strange weapon.',
        null),
       ('Common Ascension', 'Inspector''s Sacrificial Knife', 4, 29, null,
        'In the hands of its lord, this fierce weapon has handled many "debts." No-one has eyes in the back of their heads, and this weapon and its related techniques are designed around that weakness.',
        null),
       ('Common Ascension', 'Recruit''s Insignia', 1, null, null,
        'An insignia to identify the recruits. Makes one wonder about what the ones joining the Fatui''s war machine were thinking.',
        null),
       ('Common Ascension', 'Sergeant''s Insignia', 2, 31, null,
        'An insignia with a different shape to tell the sergeants from new recruits. Perhaps there are complicated emotions behind it.',
        null),
       ('Common Ascension', 'Lieutenant''s Insignia', 3, 32, null,
        'An armband to identify officers. The Fatui possess a colossal army, so there must be something extraordinary about the ones who achieved this rank within the group.',
        null),
       ('Common Ascension', 'Treasure Hoarder Insignia', 1, null, null,
        'A signet that proudly represents its owner''s position as a member of the Treasure Hoarders. The pursuit of treasure knows no bounds. That said... is being a thief something to be proud of?',
        null),
       ('Common Ascension', 'Silver Raven Insignia', 2, 34, null,
        'A raven insignia used by members of the Treasure Hoarders to identify each other. The Treasure Hoarders ask for no resume. Anyone who has an insatiable desire for treasure and is backed up by an equal amount of courage can become a worthy member.',
        null),
       ('Common Ascension', 'Golden Raven Insignia', 3, 35, null,
        'A raven insignia that symbolizes the pride and the guiding principle of the Treasure Hoarders. Whether it''s hidden amidst the vastness of the land or in the depths of the seas, as long as there are treasures to be hunted down, the spirit of Treasure Hoarders, who will stop at nothing to acquire them, will never die.',
        null),
       ('Common Ascension', 'Whopperflower Nectar', 1, null, null,
        'Nectar extracted from the stamen of a Whopperflower that contains trace amounts of elements. The taste of the nectar has a hint of Sweet Flower in it.',
        null),
       ('Common Ascension', 'Shimmering Nectar', 2, 37, null,
        'Nectar that is full of pure elements.
Scholars generally concur that Whopperflowers are advanced life forms among the elemental plants, but there has yet to be a satisfactory explanation regarding their predatory habits.',
        null),
       ('Common Ascension', 'Energy Nectar', 3, 38, null,
        'A thick and sticky honey that is full of energy. The Whopperflower hunts by tricking its prey, a process it uses to possibly evolve into a more powerful and pure form.',
        null),
       ('Common Ascension', 'Fragile Bone Shard', 2, null, null,
        'A bone shard once carried by a Geovishap Hatchling. Although they are quite fragile, they seem to still harbor some indescribable power.',
        null),
       ('Common Ascension', 'Sturdy Bone Shard', 3, 40, null,
        'A fragment of an unknown creature''s bones that appear to be prized by Geovishap Hatchlings for some reason.
The fragment appears to be quite aged. Despite being dragon-like beasts with no spoken language, they still seem to have some sort of special affection for these bone shards.',
        null),
       ('Common Ascension', 'Fossilized Bone Shard', 4, 41, null,
        'A fossilized bone fragment sometimes found after defeating Geovishap Hatchlings.
Geovishap Hatchlings all dream of growing into great dragons one day. They see these fossils as dragon bones and greatly cherish them, perhaps because they too hope to attain the dragons'' longevity and power.',
        null),
       ('Common Ascension', 'Old Handguard', 1, null, null,
        'A battle-worn handguard that was once mounted on an Inazuman blade.
For those adept in the art of the sword, the tsuba is a defense from the edge of an opponent''s blade. For beginners, it is a defense made for their own right hand, to protect it from itself.',
        null),
       ('Common Ascension', 'Kageuchi Handguard', 2, 43, null,
        'A handguard mounded upon a sword of some distinction.
Inazuma has a long tradition of sword-making. When making swords, smiths will often make several different weapons at once, before choosing from among them the "shinuchi," or the best weapon, while the others are known as "kageuchi."',
        null),
       ('Common Ascension', 'Famed Handguard', 3, 44, null,
        'An intricately-made handguard that was mounted upon a famed weapon.
Some believe that swords have souls and lives of their own, and thus deserve their own names. Those who love their blades will be acknowledged by them in turn. But those who see their swords as friends or even lovers should be warned that this relationship is built on death and bloodshed. The passions of those who dance with their blade amid crimson showers must surely be cooled someday by fickle steel.',
        null),
       ('Common Ascension', 'Chaos Gear', 2, null, null,
        'Comes from a now-inactive ancient Ruin machine.
This is the energy source of that biomimetic mechanism.', null),
       ('Common Ascension', 'Chaos Axis', 3, 46, null,
        'Comes from a now-inactive ancient Ruin machine.
Even the great techniques and unknown power of this device must come to nothing should the machine that contained them ever fail to maintain structural integrity.',
        null),
       ('Common Ascension', 'Chaos Oculus', 4, 47, null,
        'Comes from a now-inactive ancient Ruin machine.
The "Ruin" part of the name comes from the areas where they are most active. However, Ruin machines actually have little in common with the detritus in which they are often found.
In the ancient past, these ruins were once part of a civilization mighty enough to almost touch the dome of the firmament, while "ruin" still waits in the deep places of the earth, awaiting the order to arise and tread all kingdoms underfoot.',
        null),
       ('Common Ascension', 'Dismal Prism', 2, null, null,
        'This was once a prism that could polarize light, but has grown dull through the passing of years.', null),
       ('Common Ascension', 'Crystal Prism', 3, 49, null,
        'A prism that can bend light. Illusory images can be made using such prisms, giving such devices — in a manner of speaking — the power to sway human hearts.',
        null),
       ('Common Ascension', 'Polarizing Prism', 4, 50, null,
        'A prism that can bend light. In the darkness, these prisms can spread thin light into a wider area. Perhaps this is due to this quirk that these prisms can grant a measure of peace to those whose hearts are oft shrouded in darkness.',
        null),
       ('Character Ascension', 'Brilliant Diamond Sliver', 2, null, null, '"Welcome to this world."', null),
       ('Character Ascension', 'Brilliant Diamond Fragment', 3, 52, null, '"Welcome to this world."', null),
       ('Character Ascension', 'Brilliant Diamond Chunk', 4, 53, null, '"Welcome to this world."', null),
       ('Character Ascension', 'Brilliant Diamond Gemstone', 5, 54, null, '"Welcome to this world."', null),
       ('Character Ascension', 'Agnidus Agate Sliver', 2, null, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Agnidus Agate Fragment', 3, 56, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Agnidus Agate Chunk', 4, 57, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Agnidus Agate Gemstone', 5, 58, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Varunada Lazurite Sliver', 2, null, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Varunada Lazurite Fragment', 3, 60, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Varunada Lazurite Chunk', 4, 61, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Varunada Lazurite Gemstone', 5, 62, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Vajrada Amethyst Sliver', 2, null, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Vajrada Amethyst Fragment', 3, 64, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Vajrada Amethyst Chunk', 4, 65, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Vajrada Amethyst Gemstone', 5, 66, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Vayuda Turquoise Sliver', 2, null, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Vayuda Turquoise Fragment', 3, 68, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Vayuda Turquoise Chunk', 4, 69, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Vayuda Turquoise Gemstone', 5, 70, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Shivada Jade Sliver', 2, null, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Shivada Jade Fragment', 3, 72, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Shivada Jade Chunk', 4, 73, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Shivada Jade Gemstone', 5, 74, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Prithiva Topaz Sliver', 2, null, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Prithiva Topaz Fragment', 3, 76, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Prithiva Topaz Chunk', 4, 77, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Prithiva Topaz Gemstone', 5, 78, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Nagadus Emerald Sliver', 2, null, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Nagadus Emerald Fragment', 3, 80, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Nagadus Emerald Chunk', 4, 81, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Nagadus Emerald Gemstone', 5, 82, null, 'Character Ascension Material.', null),
       ('Character Ascension', 'Hurricane Seed', 4, null, null,
        'The imploded form of an Anemo Hypostasis upon its defeat. It contains the essence of Anemo energy. It is said that the power to create hurricanes resides within its seemingly fragile body. This butterfly of pure Anemo energy must be waiting for the day to conjure up storms once again.',
        null),
       ('Character Ascension', 'Lightning Prism', 4, null, null,
        'An Electro Hypostasis channels nearby elemental energy to repair damaged elemental entities. It contains the essence of Electro energy. A common prism separates white light into component colors; a Lightning Prism, however, channels flowing energy and weaves them into lightning. It will continue to do so even after the Electro Hypostasis has been defeated.',
        null),
       ('Character Ascension', 'Basalt Pillar', 4, null, null,
        'A pillar form by the shell of a Geo Hypostasis. It is composed of high-density Geo energy. This is the heaviest component of a Geo Element. Maybe the reason a Geo Hypostasis creates this polar out of its shell and raises itself is just to get closer to the sky, not to combat enemies.',
        null),
       ('Character Ascension', 'Hoarfrost Core', 4, null, null,
        'The exposed core of a defeated Cryo Regisvine. Pure cryo elements are contained within it. Energy and thoughts that swell deep within the earth will eventually erupt on the surface. Even the deathly silent frost will attach to creatures on the ground, causing even the vines and branches of vegetation to become huge and fierce, attracting the hunter''s gaze.',
        null),
       ('Character Ascension', 'Everflame Seed', 4, null, null,
        'A seed that fuels the unending flames of the Pyro Regisvine. It emits pyro energy as if it will burn all that has ever sprouted from the ground.
Endless desires flow among turbulent energy deep within the earth. What desire could steadily hold such fire to the plants and long so eagerly to bathe everything in unquenchable flames?',
        null),
       ('Character Ascension', 'Cleansing Heart', 4, null, null,
        'A scoop of eternal water left by an oceanid.
Though it has already diffused among the depths of the lake, its purity remains all the same. But why would a creature so pure and clean as an oceanid desire the appearance of plants born of the ground and assume such a form with pure water? They need not breathe nor do they require sustenance...',
        null),
       ('Character Ascension', 'Juvenile Jade', 4, null, null,
        'A crystalline substance taken from a Primo Geovishap. Within it is contained the potential to become a dragon.
These dull crystals are precipitated within the bodies of vishaps sleeping in the mountains. Liyue folklore holds that they will gather power over many years, after which this crystal will, at last, replace their original heart, and the vishap will become a true dragon — one that can shake the mountains and split the earth..',
        null),
       ('Character Ascension', 'Marionette Core', 4, null, null,
        'This core can power the inorganic Maguu Kenki and cause it to wield a blade like a living being.
Flesh decays, and with it decay all martial arts mastery and all poignant memories.
Perhaps only by converting one''s four limbs and body into sturdy mechanical parts, and by at last sacrificing one''s very own heart for a sophisticated mechanical one, can one transcend the impermanence of the fleshly form...',
        null),
       ('Character Ascension', 'Perpetual Heart', 4, null, null,
        'The core that powers the autonomous movements of the Perpetual Mechanical Array.
Some theorize that the symbols on these cores have knowledge and logic inscribed upon them in a language that eyes cannot perceive. Some go a step further and believe that these unique Ruin machines autonomously decided to forsake a biomimetic form to pursue strength of function on account of their especially large cores and complex inscriptions.',
        null),
       ('Character Ascension', 'Smoldering Pearl', 4, null, null,
        'A crystallization of a Pyro Hypostasis that constantly emits heat.
Even the burning flames shall one day grow cold, and even the ashen firewood can will itself back into a raging blaze. It must then be the will of the world that Pyro Hypostases should constantly cool down and heat up, much like the universe teems with endless life... until the fated darkness shall one day descend and bring it all to naught.',
        null),
       ('Character Ascension', 'Crystalline Bloom', 4, null, null,
        'An ice crystal of exceeding purity that is created in the frigid blooming of a Cryo Hypostasis.
These frosty crystals will continue to grow according to their own cold, rigid laws, till one day a flower of winter shall bloom and freeze everything. Perhaps it is stagnant time, that never-thawing bosom, that is the essence of this undying flower.',
        null),
       ('Character Ascension', 'Dew of Repudiation', 4, null, null,
        'A strange water droplet left behind by the collapse of the Hydro Hypostasis.
It has strong rejection properties, and this forms the basis of one of the Hydro Hypostasis'' attack patterns as well. They say that water contains memories and willpower, and that these things can grow when bodies of water meld together. However, the waves conjured by the Hydro Hypostasis are incompatible with the currents that flow above and below ground. Even if it were to flow into the surpassingly pure waters of Petrichor, this drop of water will likely resist assimilation as strongly as mercury.',
        null),
       ('Character Ascension', 'Storm Beads', 4, null, null,
        'Crackling Electro pearls left behind by the Thunder Manifestation.
It is said that Thunder Manifestations will only descend upon lands where powerful hatred dwells. The singers say that it is the unbearable disappointments and sufferings of life that drive them to forever wander the broken earth, unleashing sky-searing lightning as they go.',
        null),
       ('Character Talent', 'Teachings of Freedom', 2, null, null, 'Freedom is the spirit of the Land of the Wind.
The freedom to live is one of such. It is the freedom to live freely and healthily without concerns of one''s own safety.',
        null),
       ('Character Talent', 'Guide to Freedom', 3, 97, null, 'Freedom is the spirit of the Land of the Wind.
The freedom of travel is one of such. It is the freedom to traverse the land freely without being obstructed.', null),
       ('Character Talent', 'Philosophies of Freedom', 4, 98, null, 'Freedom is the spirit of the city of wind.
To sing is one such freedom. To sing on the land created by the Anemo Archon is to send your heart away with the song on the wind.',
        null),
       ('Character Talent', 'Teachings of Resistance', 2, null, null, 'Resistance is the backbone of the Land of the Wind.
The history of Mondstadt is one of resistances. People rose up to prevent past conflicts from ever being forgotten, like sprouts breaking through the soil, like the eternal wind eroding through stone walls.',
        null),
       ('Character Talent', 'Guide to Resistance', 3, 100, null, 'Resistance is the backbone of the city of Wind.
The history of Mondstadt is one of resistances. People rose up to grant the citizens of Mondstadt the freedom they now enjoy, like the Anemo Archon blowing away the snow, or like Vennessa rising up to fight.',
        null),
       ('Character Talent', 'Philosophies of Resistance', 4, 101, null, 'Resistance is the backbone of the Land of the Wind.
The history of Mondstadt is one of resistances. People rose up to allow the future Mondstadt''s poetry to freely be that of the wind and be spread across the land.',
        null),
       ('Character Talent', 'Teachings of Ballad', 2, null, null, 'Poetry is the soul of the Land of the Wind.
Poetry is the manifestations of beautiful feelings. On a beautiful day, the breezes carry with them poetry that touches the heart of people like the wind caressing the leaves.',
        null),
       ('Character Talent', 'Guide to Ballad', 3, 103, null, 'Poetry is the soul of the Land of the Wind.
Poetry is the manifestations of the will to encourage. In the dark days, the gales in the streets and alleyways whisper words of fury, like the battle drums, like the low rumbling before the storm.',
        null),
       ('Character Talent', 'Philosophies of Ballad', 4, 104, null, 'Poetry is the soul of the Land of the Wind.
Poetry is the manifestations of the desire to spread the word. Though nothing is eternal, though nothing will be the same, the wind''s poetry will still spread beyond the skies, the land, the seas, to every corner of the world.',
        null),
       ('Character Talent', 'Teachings of Prosperity', 2, null, null,
        'Prosperity is the pursuit of the land of the earth. Prosperity is the blessing of Liyue, is the great city built by the gods and the people of Liyue, is the source of the peace and safety of the land.',
        null),
       ('Character Talent', 'Guide to Prosperity', 3, 106, null,
        'Prosperity is the pursuit of the Land of the Earth. Prosperity is the promise made by Liyue to its children: To repay the hard-working laborers with enough gold to brighten up this land.',
        null),
       ('Character Talent', 'Philosophies of Prosperity', 4, 107, null,
        'Prosperity is the pursuit of the Land of the Earth. Prosperity is Liyue''s past, present, and future. This prosperity, unmatched and unobtainable by any of the other nations, is all for Liyue and its children to enjoy.',
        null),
       ('Character Talent', 'Teachings of Diligence', 2, null, null, 'Industriousness is the foundation of the Land of the Earth.
Diligence is to conquer mountains and seas, pursue prosperity, golden bravery, and power with honest, hard work.',
        null),
       ('Character Talent', 'Guide to Diligence', 3, 109, null, 'Industriousness is the foundation of the Land of the Earth.
Industriousness is the catalyst the flows in the blood of the people of Liyue, able to turn rocks into gold.
It is what makes its great commercial port great.', null),
       ('Character Talent', 'Philosophies of Diligence', 4, 110, null, 'Industriousness is the foundation of the land of the earth.
Industriousness is believing in one''s own ability to earn a place in the land of the gods through sweat, wisdom, and power.',
        null),
       ('Character Talent', 'Teachings of Gold', 2, null, null, 'Gold is the symbol of the Land of the Earth.
Gold is the blood flowing deep under the land of Liyue, is the muscles that pump Liyue''s heart, and the bones that make Liyue stand proud.',
        null),
       ('Character Talent', 'Guide to Gold', 3, 112, null, 'Gold is the symbol of the Land of the Earth.
Gold symbolizes conversion. This is the unspoken understanding between Liyue''s mountains, land, city, and its people. In Liyue, industriousness is converted to gold, and gold to prosperity.',
        null),
       ('Character Talent', 'Philosophies of Gold', 4, 113, null, 'Gold is the symbol of the Land of the Earth.
Gold is the wealth of Liyue, but Liyue''s true wealth is the hearts of its people that shine like gold.', null),
       ('Character Talent', 'Teachings of Transience', 2, null, null, 'Transience is the dream of the nation of thunder.
Fleeting glories are the highest expression of mortal beauty, for are we mortals not like the flashing lightning itself? Like a lovely dream or blossoming spark, we shall leave a gorgeous mark on the eternal night sky.',
        null),
       ('Character Talent', 'Guide to Transience', 3, 115, null, 'Transience is the dream of the nation of thunder.
We find the greatest joys in mortal life in transient dreams, for is life itself not like the shadow of the thunder? Pursue your dreams into the clouds if you wish, and enjoy the unexpected silence of the dim lamp-lit nights.',
        null),
       ('Character Talent', 'Philosophies of Transience', 4, 116, null, 'Transience is the dream of the nation of thunder.
The fleeting nature of this mortal world is the essence of beauty, for are our lives in this world not akin to the levin flash? Yet the might of the divine comes suddenly, and before the roar of eternity, who can stand?',
        null),
       ('Character Talent', 'Teachings of Elegance', 2, null, null, 'Elegance is the form of the nation of thunder.
Elegance brooks no flattery, and the elegant are ever noble. They are like the sea eagles who soar on high to contend with the resounding storms. They will not cater to philistine vulgarity, as one would not cast a flower crown into the mud, staining its dignity.',
        null),
       ('Character Talent', 'Guide to Elegance', 3, 118, null, 'Elegance is the form of the nation of thunder.
Elegance shuns arrogance. The elegant are ever humble, and only by discarding vanity and sloth may one see clearly — and is there not beauty and loveliness even in the basest of appearances?',
        null),
       ('Character Talent', 'Philosophies of Elegance', 4, 119, null, 'Elegance is the form of the nation of thunder.
Elegance abhors vulgarity, and the elegant ever walk alone. Resisting base evils, unmoved by base loves, never taking refuge in base ignorance — that is how one perceives the chasm between the elegant and the contemptuous.',
        null),
       ('Character Talent', 'Teachings of Light', 2, null, null, 'Light is the yearning of the land of thunder.
The ruler who claims to have perceived all forever aims to hoard celestial glory. But this vision that cannot be shared only leads people to long for it more fiercely, like moths diving into the flame.',
        null),
       ('Character Talent', 'Guide to Light', 3, 121, null, 'Light is the yearning of the land of thunder.
Though the sun rays themselves should be blocked by layers upon layers of clouds, there are still those in the thunder god''s land who dream of piercing that wrathful sea of lightning to pursue the glory of the divine, fearing not that they shall be cruelly struck down.',
        null),
       ('Character Talent', 'Philosophies of Light', 4, 122, null, 'Light is the yearning of the land of thunder.
Though they must live forever on the earth, humanity will always reach for the light. Mortals will pursue and surpass, and they will never stop. A sealed eternity may, perhaps, look magnificent, but its essence is death.',
        null),
       ('Character Talent', 'Crown of Insight', 5, null, null,
        'Once a medium for the storage and transfer of wisdom in ancient times. Now wisdom is found in ancient texts and in profound speech. Nevertheless, this Crown of Insight must still be able to impart some transcendent power and wisdom to its bearer.',
        null),
       ('Character Talent', 'Dvalin''s Plume', 5, null, null, 'A feather from the tail of the Dragon of the East.
As a dragon''s feather it has experienced more than a thousand years'' worth of winds. Its ambition to be free almost evokes light breezes to break it off its current shackles, but its previous owner''s recognition of you has kept it in your hands.',
        null),
       ('Character Talent', 'Dvalin''s Claw', 5, null, null, 'A claw from the Dragon of the East.
As it had once torn through the flesh of the shadow dragon Durin, it used to contain his vicious poison. However, thanks to your purification and healing, it is no longer toxic.',
        null),
       ('Character Talent', 'Dvalin''s Sigh', 5, null, null, 'A bit of power taken from the whirlwinds evoked by the Dragon of the East.
Beautiful and transparent, both trade winds and tornadoes will work in its name. The winds moves as its companion, its voice, and its freedom.
Its enemies are the thousands who stand against the wind.', null),
       ('Character Talent', 'Tail of Boreas', 5, null, null,
        'A handful of tail scales from the Great Wolf King of the North. Even without its physical body and beyond death, Andrius still possesses extraordinary powers. It took a form comprised of ice and wind to embrace a new challenge, but even such form could not house all of its power. The ice scales that fell during the battle still retain some of its spiritual energy.',
        null),
       ('Character Talent', 'Ring of Boreas', 5, null, null, 'A bit of crystallized ice from the Great Wolf King of the North.
This land was once a realm of sub-zero blizzards and ice storms filled with razor-sharp ice shards, all at the command of Boreas. Though its powers may have diminished, flash-freezing the land is still a breeze.',
        null),
       ('Character Talent', 'Spirit Locket of Boreas', 5, null, null,
        'A bit of the Great Wolf King of the North''s power drawn from its soul. This land was once a realm of sub-zero blizzards and ice storms filled with razor-sharp ice shards, all at the command of Boreas. In its final moments, it finally realized the chilling north wind could only extinguish life, not nurture it; therefore, Boreas let its powers freely flow into the land to protect it and its inhabitants.',
        null),
       ('Character Talent', 'Tusk of Monoceros Caeli', 5, null, null, 'The horn of a whale that you obtained from defeating Childe, who had unleashed the might of his Delusion.
It is said that the shape of one''s constellation determines one''s character. The image of a whale cruising across the celestial heights represents a solipsism that seeks to crush and devour all in its path.
Embracing this aspect of himself, Childe gleefully summoned one such beast before throwing himself into battle against you.',
        null),
       ('Character Talent', 'Shard of a Foul Legacy', 5, null, null, 'The shard of a weapon that you obtained from defeating Childe, who had unleashed the might of his Delusion.
It is stained with a profound color that is not of this world, no doubt due to the land of endless darkness that the young boy saw with his own two eyes.
Perhaps it has nothing to do with the power of a Delusion, but as they say, the weapon reflects its user...', null),
       ('Character Talent', 'Shadow of the Warrior', 5, null, null, 'A fragment of power that you obtained from defeating Childe, who had unleashed the might of his Delusion.
It is the product of a will to fight that has been honed over countless slaughters.
If humans do indeed have destinies, then his must surely have been twisted by such deeds. Why else, then, would he always be at the heart of every conflict?',
        null),
       ('Character Talent', 'Dragon Lord''s Crown', 5, null, null, 'Horns created from hardened jade crystallized over a thousand years are the natural crown of the dragon king.
Infused with spirit and carved from bedrock, it was born from the mountain''s heart to show the strength of the earth to the land amidst monoliths, and its long golden horns are the mark of its ancient strife with an ancient lord.
For a time, this horn was shattered and lost its luster, but now it gleams cold and gold as it sits in your palm.',
        null),
       ('Character Talent', 'Bloodjade Branch', 5, null, null, 'Nurtured by the might of the dragon king, these bone branches glitter with strange, unique colors.
Hatred coursed through the natural streams and kissed the cold moonlight, and from them were these crystalline branches born and grown...
Even though they were severed in battle, these branches steeped in dragon blood rustle as if eternally ill-at-ease.',
        null),
       ('Character Talent', 'Gilded Scale', 5, null, null, 'Scaled armor that grows naturally over mystical stone, tough and silent, and filled with the strength of the dragon king.
Across the years as countless generations returned to the mulch of the earth, gold and obsidian embedded themselves into flesh and blood forged from bedrock before spreading and turning into scales.
Searing agony, wordless cries... perhaps they will all vanish when the grudges that spawned them, too, finally come to an end.',
        null),
       ('Character Talent', 'La Signora 1', 5, null, null, '', null),
       ('Character Talent', 'La Signora 2', 5, null, null, '', null),
       ('Character Talent', 'La Signora 3', 5, null, null, '', null),
       ('Local Specialities', 'Wolfhook', 1, null, null,
        'A berry with thorns that often gets attached to a wolf''s pelt. When you look at it, you can almost hear the echoing cries of the wolves in the woods.',
        1),
       ('Local Specialities', 'Valberry', 1, null, null,
        'A plump and translucent berry that has a fragrant smell and a sweet refreshing taste. In the past, the watchers of the storms found solace in the sweetness of the fruit and the hope for the city''s security.',
        1),
       ('Local Specialities', 'Cecilia', 1, null, null,
        'A beautiful flower with a name that suits its appearance. It only grows where harsh winds blow, and is just as intangible as the true heart of an unbound soul.',
        1),
       ('Local Specialities', 'Windwheel Aster', 1, null, null,
        'A plant that adores the wind. To the proud children of the wind, or the citizens of Mondstadt, the Windwheel Asters are the "visible winds."',
        1),
       ('Local Specialities', 'Philanemo Mushroom', 1, null, null,
        'A fungus that grows in the warm caress of the wind. It is as everlasting as the wind, nourishing life.', 1),
       ('Local Specialities', 'Small Lamp Grass', 1, null, null,
        'A wild grass that emits light at night. Used in cooking to enhance other flavors.', 1),
       ('Local Specialities', 'Calla Lily', 1, null, null,
        'A flower that grows near water sources. When cooked the petals have a chunky texture, yet are sweet and a little bitter.',
        1),
       ('Local Specialities', 'Dandelion Seed', 1, null, null,
        'A tiny seed that rides on the wind. Even without its feathered wings, it still holds the hope from afar within.',
        1),
       ('Local Specialities', 'Jueyun Chili', 1, null, null, 'A spicy plant native to Liyue.
Merely smelling it makes one hot and thirsty.', 2),
       ('Local Specialities', 'Noctilucous Jade', 1, null, null,
        'A rare mineral that glimmers in the dark. It''s said to be a mutated gemstone condensed from the flourishing elements of the world.',
        2),
       ('Local Specialities', 'Silk Flower', 1, null, null,
        'A crimson flower that blooms like the rainbow clouds in Liyue. It can be made into silky-smooth fabric.', 2),
       ('Local Specialities', 'Glaze Lily', 1, null, null,
        'An extremely ancient flower that was said to be commonly seen in Liyue. It transforms the memories of the land into its fragrance during florescence.',
        2),
       ('Local Specialities', 'Qingxin', 1, null, null,
        'A translucent white flower that only grows on the highest stone peaks. It eschews the warmth and moisture of the plains to gaze out afar from the solitary mountaintops.',
        2),
       ('Local Specialities', 'Starconch', 1, null, null,
        'Empty seashells brought ashore by the tides. Hold it close to your ear, and hear the longing calls of the sea.',
        2),
       ('Local Specialities', 'Violetgrass', 1, null, null,
        'A small flower with strong vitality. It was said its downward-blooming flower keeps its fragrance from dissipating.',
        2),
       ('Local Specialities', 'Cor Lapis', 1, null, null,
        'A precious crystal of condensed pure Geo element that usually grows along with other minerals. It''s also commonly called "Cor Petrae."',
        2),
       ('Local Specialities', 'Onikabuto', 1, null, null,
        'A strange beetle that inhabits areas rich with Electro energy. Its docile and sedentary temperament could not be more different from the fierce, demonic visage displayed on its armored shell.',
        3),
       ('Local Specialities', 'Sakura Bloom', 1, null, null,
        'Blossoms from the Sacred Sakura at the Grand Narukami Shrine, filled with a fondness for Inazuma.', 3),
       ('Local Specialities', 'Crystal Marrow', 1, null, null,
        'A crystal that contains a sliver of Tatarigami power. Adding this material during smelting will greatly increase the strength and toughness of metals.',
        3),
       ('Local Specialities', 'Dendrobium', 1, null, null,
        'A vibrant plant that has also been named the "lycoris" by the poets. It was once thought extinct in the Inazuman archipelago, only to re-emerge now upon the battlefields. It is said that it blooms most enchantingly where much blood was spilled.',
        3),
       ('Local Specialities', 'Naku Weed', 1, null, null,
        'Even on windless days, this plant will tremble lightly amid the cries of thunder. The part of it that resembles petals are in fact extensions of the leaves meant to protect the fragile flower.',
        3),
       ('Local Specialities', 'Sea Ganoderma', 1, null, null,
        'A plant species that only grows in certain regions and islands of the ocean. Though it looks like a fungus of some sort, it actually comes from a substance secreted by certain soft-bodied organisms.',
        3),
       ('Weapon Enhancement', 'Enhancement Ore', 1, null, 'Weapon EXP material. Gives 400 EXP.',
        'A refined ingot with endless possibilities that can be used to enhance weapons.', null),
       ('Weapon Enhancement', 'Fine Enhancement Ore', 1, 162, 'Weapon EXP material. Gives 2,000 EXP.',
        'For reasons unknown, this special and refined ore can be absorbed by weapons to greatly increase their strengths.',
        null),
       ('Weapon Enhancement', 'Mystic Enhancement Ore', 1, 163, 'Weapon EXP material. Gives 10,000 EXP.',
        'Legend has it that this refined ingot contains the memories of battles that had taken place on the land. The weapons that benefit from these memories naturally become sentient.',
        null),
       ('Weapon Ascension', 'Tile of Decarabian''s Tower', 2, null, null,
        'The place now known as Stormterror''s Lair was once the capital city of Decarabian, the God of Storms. Since this dream of prosperity was created entirely by his divine might, the broken pieces left behind by the shattering of that dream still possess great power.',
        null),
       ('Weapon Ascension', 'Debris of Decarabian''s City', 3, 165, null,
        'Decarabian, the God of Storms, was content with the capital city he had raised, and accepted the worship of the people from atop his tower. But he knew not that the people did not bow to him out of respect or adoration.',
        null),
       ('Weapon Ascension', 'Fragment of Decarabian''s Epic', 4, 166, null,
        'Andrius once declared war upon Decarabian, but failed to even scratch the capital of the Lord of the Tower. If it were not for the song of freedom that shattered the city in an instant, Decarabian''s dream would have gone on forever.',
        null),
       ('Weapon Ascension', 'Scattered Piece of Decarabian''s Dream', 5, 167, null, 'The people did not bow to Decarabian out of respect or adoration, but because the harsh winds had laid them low. This was the shattered dream and ambition of the Anemo Archon before the rise of Barbatos.
He tried so hard to make his dream come true, and so the fragments of that dream are still mighty.', null),
       ('Weapon Ascension', 'Boreal Wolf''s Milk Tooth', 2, null, null, 'Andrius'' wolf pack is its blessed honor guard, and even the milk teeth of a wolf''s cub possess great potential.
In the past, the gods had the responsibility to love all people, which made Andrius quite the oddball for only adopting abandoned babies and accepting wanderers.',
        null),
       ('Weapon Ascension', 'Boreal Wolf''s Cracked Tooth', 3, 169, null, 'The life of a wolf is not without violence; broken bones or cracked teeth are nothing special.
Andrius found humans to be a disappointment, but believed babies to be innocent. If both the wolf pack and the adopted children chose each other, then they become a Lupical, a fated family.',
        null),
       ('Weapon Ascension', 'Boreal Wolf''s Broken Fang', 4, 170, null, 'The wolf pack also understands that humans are not solitary creatures. The honorary broken tooth is a parting gift said to bring protection and luck.
In the legends of a far-off world, a female wolf once adopted two great humans. Their home was known as the Cave of Wolves, or Lupercal - that word meaning the same thing as Lupical does in this world.',
        null),
       ('Weapon Ascension', 'Boreal Wolf''s Nostalgia', 5, 171, null,
        'The Wolf King, believing itself to despise humans, thought itself unable to envision a happy life for humanity, making it unworthy of becoming the Lord of the Winds of the world. Therefore, it chose to disappear. Yet, in truth, it gazed on the ones the world abandoned ever so gently.',
        null),
       ('Weapon Ascension', 'Fetters of the Dandelion Gladiator', 2, null, null, 'It''s a human thing to exaggerate on a hero''s story, even to the point of elevating the fetters that once bound the hero to the level of an enemy of true freedom.
As a result, these fetters were granted extraordinary powers.', null),
       ('Weapon Ascension', 'Chains of the Dandelion Gladiator', 3, 173, null,
        'The chains that once bound the great hero Vennessa. In truth, all gladiators would have worn chains in that era, and Vennessa was but one of them.',
        null),
       ('Weapon Ascension', 'Shackles of the Dandelion Gladiator', 4, 174, null, 'Vennessa was not truly bound by her chains. If she had so wished, no ordinary physical constraints forged in Mondstadt could have held her, for the land there yielded no ore of exceptional quality, nor did it possess the divine flame of her ancestral home.
She was only bound by her responsibility to take care of her tribespeople.', null),
       ('Weapon Ascension', 'Dream of the Dandelion Gladiator', 5, 175, null, 'Vennessa was freed from her slavery, but that which constrained her only grew greater - from her tribesmen to all of Mondstadt, and even to the concept of freedom itself, extending to the whole world.
What she really hoped for, in truth, was that the world might grow stronger.', null),
       ('Weapon Ascension', 'Luminous Sands from Guyun', 2, null, null,
        'The stone pillars that tower amid the Guyun Stone Forest were once the stone lances Morax used to defeat his enemies. As time passed, the body of these gods penetrated into the pillars, granting them divinity. The pillars would sometimes shed crumbs of hatred and curses.',
        null),
       ('Weapon Ascension', 'Lustrous Stone from Guyun', 3, 177, null,
        'To the informed, Guyun Stone Forest is not some miraculous sight on the sea to behold, but the cemetery of the former gods of Liyue. Hatred and filth have periodically raised up from it, but all have been subdued by a demon-conquering young man.',
        null),
       ('Weapon Ascension', 'Relic from Guyun', 4, 178, null,
        'The stone lance has a glimmering core formed by the power of the defeated gods. Their hatred is not directed at Morax, for they have lost themselves a long time ago and are incapable of holding personal grudges.',
        null),
       ('Weapon Ascension', 'Divine Body from Guyun', 5, 179, null,
        'That which lurks within and animates this relic are the divine remains of lamenting gods. They are unrealized ideals, designs for a prosperous humanity that could never be. They may now lie deep within stone and sea, but they will not go quietly into the night.',
        null),
       ('Weapon Ascension', 'Mist Veiled Lead Elixir', 2, null, null,
        'Jueyun Karst is the realm of the mighty and illuminated adepti. But other than the ability to control the elements of the world, Jueyun Karst is also home to three other untold secrets: Danding (Alchemy), Fulu (Sigils), and Waijing (Sub-Space Creation).',
        null),
       ('Weapon Ascension', 'Mist Veiled Mercury Elixir', 3, 181, null,
        'With Fulu (Sigils), the adepti can store their power in the form of symbols, and with Waijing (Sub-Space Creation) they can fashion a cosmic paradise with the power of their minds. The manufacture of elixirs, however, has always been shrouded in mystery, for certain death follows for any who swallow them.',
        null),
       ('Weapon Ascension', 'Mist Veiled Gold Elixir', 4, 182, null, 'Elixirs are in fact pills made from metal alloys. They were created by the adepti, and are able to grant weapons transcendent powers.
However, they are rarely seen in the world due to the hubris of the practitioners of martial arts, who prized the ways of combat over the paths of the adepti.',
        null),
       ('Weapon Ascension', 'Mist Veiled Primo Elixir', 5, 183, null,
        'An elixir of the highest quality. It embodies a state of intertwining order and chaos, and is said to mirror how the world was when it was first created. Of course, a certain someone knows that this was not the case.',
        null),
       ('Weapon Ascension', 'Grain of Aerosiderite', 2, null, null,
        'A black meteor once fell beyond Liyue''s Sea of Clouds, said to have fallen to vanquish a monster. However, it was stained by powerful tainted blood, so this item no longer possesses the pure power of Rex Lapis.',
        null),
       ('Weapon Ascension', 'Piece of Aerosiderite', 3, 185, null, 'Rumors of sea monsters are commonplace in Liyue, since the other-shore is an unknown region that lies outside of Teyvat.
Without the protection of The Seven, all that lies beyond is unknown chaos. Only power beyond the order of Teyvat is able to stain the power of Rex Lapis black.',
        null),
       ('Weapon Ascension', 'Bit of Aerosiderite', 4, 186, null,
        'The coastal nations of Teyvat refer to the region beyond the protection of The Seven as the Dark Sea. It is said many defeated gods refused to live under the new order of The Seven, so they fled to remote islands and became evil gods. However, their powers came from the same source as Rex Lapis, separate from this all-devouring darkness.',
        null),
       ('Weapon Ascension', 'Chunk of Aerosiderite', 5, 187, null,
        'When Khaenri''ah was destroyed, a great sinner created endless monsters with alien, dark blood flowing through their veins. They rampaged across the land, destroying all in their paths. Their lives were mutations, caused by powers beyond this world. The black serpentine dragon Durin that attacked Mondstadt was such a mutation.',
        null),
       ('Weapon Ascension', 'Coral Branch of a Distant Sea', 2, null, null,
        'Watatsumi Island is the furthest from Narukami Island in the Inazuman island chain, and its name means "the god of the oceans" in the island''s ancient tongue. Legend has it that when the great serpent first arose within the abyssal nation of ever-night, its fluorescent body was covered in myriad-colored coral.',
        null),
       ('Weapon Ascension', 'Jeweled Branch of a Distant Sea', 3, 189, null,
        'This coral cannot be found anywhere in Teyvat, but was a gift that the great serpent obtained when it broke into the Dark Sea. For that abyssal snake, to be filled with coral was to be mighty, and its power would be shaved away as those corals were lost. In other words, those corals contain power far beyond the norm.',
        null),
       ('Weapon Ascension', 'Jade Branch of a Distant Sea', 4, 190, null, 'Fleeing into the Dark Sea, the god that had lost everything met the abandoned people who had nothing within the ocean depths. Thus it elected to remain and become their "Orobashi no Mikoto," their "Watatsumi Omikami."
It is said that the great snake god once broke off all the coral branches on its body to give light to the children who were curled up in the darkness. They also say that it used these coral branches to create a huge ladder to allow those children to once again reach the surface and see the light of day.',
        null),
       ('Weapon Ascension', 'Golden Branch of a Distant Sea', 5, 191, null, 'The meaning that lies behind the name "Watatsumi" is simply the unrequited hopes that the abandoned people who dwelt in the deep sea pinned upon the serpent god that led them.
And it was also because the serpent god now had people who worshiped it that it stayed in the world it should have long fled, breaking off the coral branches that adorned its body, treading upon land where it should not have, and facing a foe it could never hope to match — till at last, its divine form was sundered along with the mountains, its ichor turned into plasma, and its will and power became a curse that could never be extinguished: Tatarigami.',
        null),
       ('Weapon Ascension', 'Narukami''s Wisdom', 2, null, null,
        'In the past, the ancients would climb the peak now known as Mt. Yougou and bend wood that had been charred by lightning into a hook to offer as an effigy unto the thundering force that lit up the skies and shook the earth. This shape would eventually become the "Electro Mitsudomoe" symbol, symbolizing the favor, wisdom, and might of Electro, and also the people who represent these values.',
        null),
       ('Weapon Ascension', 'Narukami''s Joy', 3, 193, null,
        'Those who belong to the Shogunate Commissions are those who administer and exercise power. In the monster-filled tales of the ancient past, those who were deeply trusted by the Shogun would bear talismans with this hooked design on their person, and just as the word "commission" means to "joyfully serve" in the old tongue, those who received her favor would return it with love and loyalty. Yet, after a certain point in time, nothing would be as it was before.',
        null),
       ('Weapon Ascension', 'Narukami''s Affection', 4, 194, null, 'All demons who wander in the wilderness or live amongst mortals will be attracted by the sight of the Almighty Narukami Ogosho, represented by the Electro Mitsudomoe. Though their lives may be longer than any creature, they will at last come to their end. If those with limited lifespans hanker after eternity, then they can only pray that "Eternity" remembers them. And she did indeed answer their prayers, remembering them all, friend and foe alike, in her heart. No matter whether it was the demon owls who resided amidst the fog and ripped through the skies, the bake-danuki who dared to trespass her imperial gardens, or that female oni, lovely as the moon and mighty in battle, yet who would eventually come to blows with her... Whether it was the tengu who soared on dark wings or the Kitsune Saiguu who once walked by her side, but who eventually disappeared forever...
These countless tales have come to rest within her heart, and someday, they will surely shine again in the eternal paradise of her dreams.',
        null),
       ('Weapon Ascension', 'Narukami''s Valor', 5, 195, null, 'The treasure of the lord of thunder is her majesty, and that majesty is embodied in her valor and wrath. Her wrath comes from the love that persists in her heart, and her valor supports that anger. Thus, whomsoever should block the path towards eternity or lay a finger on Inazuma''s people shall become her foe.
They say that there were four great spirits, three divine foxes, and two great swords — but that the symbol of Her Excellency, the Almighty Narukami Ogosho, could only be a single strike, unsurpassed and brilliant as a meteor.',
        null),
       ('Weapon Ascension', 'Mask of the Wicked Lieutenant', 2, null, null, 'Folktales tell that once upon a time, there lived an oni named Torachiyo. Torachiyo was a highly skilled warrior, such that it was once said the Torachiyo might dance amid a thousand blades, juunihitoe robes becoming shredded like falling violet petals, and yet not receive a single wound. Yet this oni would eventually betray the Shogun and revolt, becoming shorn of an arm and a horn in the battle before fleeing and slaying itself in a fit of furious madness.
Hearsay holds that the stubborn oni often hold fear and distress in their hearts. That they should fantasize about eternity yet fear the moment, and are apt to become swallowed by terror or anger is their just reward. This mask depicts Torachiyo, fangs bared.',
        null),
       ('Weapon Ascension', 'Mask of the Tiger''s Bite', 3, 197, null, '"Sumirezome Sangetsu Kogetsukan" depicts the fierce oni Torachiyo shattering the Shogun''s naginata with a single bite, thus gaining the upper hand for a time. As such, masks that are based on him have finely crafted fangs.
In the denouement of this tale, the wounded oni fled into the forest, deathly afraid of showing himself even to the cold moonlight. The wind that whispers through the alleys and valleys can be said to resemble his quiet cries of agony, and so there is a poetic seasonal expression for this in Inazuma: "Torachiyo''s Wind."',
        null),
       ('Weapon Ascension', 'Mask of the One-Horned', 4, 198, null, 'In the lost songs of the oni nursemaids, Torachiyo was an elegant young man, strong of body and fair of face. He was once a beloved lieutenant of the Shogun, and he followed her into the dark abyssal realms to repel the defiled ones, winning renown for the oni, whose blood thinned with each passing day.
None now sing these songs, but the mask of a horned oni, even in a different form, still possesses power beyond the norm.',
        null),
       ('Weapon Ascension', 'Mask of the Kijin', 5, 199, null, 'Chiyo, a warrior of the oni tribe with the Electro Mitsudomoe emblem emblazoned on her back, was once swallowed whole by a beast from beyond this world that had a tiger''s body and a serpent''s tail while holding back the forces of darkness. At last, she tore the creature''s innards apart from within, breaking free.
This is the origin of the phrase "Chiyo the Tiger-Bite," and would be changed over many years to "Torachiyo."
But within the belly of the beast, she was stained by a deep sin and saw her comrades ripped to shreds by those blood-red teeth. Steeped in darkness as far as the eye could see, she would eventually draw her sword upon the Almighty Narukami Ogosho. Her sword-arm and one horn would be cloven, and she would flee from the city into the forest like a wounded beast. There, they say that she was taken for some unknown monster and slain by the tengu, or perhaps by the Shiyuumatsu-Ban — or perhaps by a scion of the Iwakura Clan training deep in the mountains, for her features had been twisted by hatred and the agony of her wounds. Or perhaps she even met the oni-masked, sword-bearing doll near the corpse of the giant serpent, and there ended her life''s journey.
Few among those who fought against the abyss in those days were spared pitch-dark dreams. Those who slew monsters and then became them were hardly the minority. The border between worlds grows fragile, and corruption of this kind is perhaps not merely monodirectional.',
        null),
       ('Weapon Refinement', 'Festering Dragon Marrow', 4, null,
        'Specialized refinement material for Festering Desire.',
        'This is the product of purifying Durin''s vile venom, which has seeped into and spread throughout Dragonspine''s ley lines. By using it on a bloodthirsty sword with a strong affinity for such materials, you can increase that sword''s power.',
        null),
       ('Weapon Refinement', '"The Visible Winds"', 4, null, 'Specialized refinement material for Windblume Ode.',
        'An intricately-made ornament that symbolizes the windmills and windblumes, and is that which adorns the limbs of the Windblume Ode. The wind is invisible and intangible, but the windmills that keep turning and the swaying flowers in the emerald fields are "the visible winds" that show people that the breeze will always care for all life in Mondstadt.',
        null),
       ('Weapon Refinement', '"Fragments of Innocence"', 4, null, 'Specialized refinement material for "Dodoco Tales."',
        'Pages scattered on the wind. Each one is filled to the brim with childlike wonder, and their dimensions are an exact match for "Dodoco Tales." The abundant innocence and pure love therein will never fade, and just like the never-ending adventure in the book — this passionate fairy tale shall forever soar in the wake of the author''s footsteps.',
        null);
insert into experiences (item, amount, moras)
values (1, 1000, 200),
       (2, 5000, 1000),
       (3, 20000, 4000);

insert into characters (label, title, allegiance, element, weapon, rarity, birthday, astrolab, cn_seiyuu, en_seiyuu,
                        jp_seiyuu, kr_seiyuu, description)
values ('Ganyu', 'Plenilune Gaze', 'Yuehai Pavilion', 'Cryo', 'Bow', 5, '02-12', 'Sinae Unicornis', '林簌 (Su Lin)',
        'Jennifer Losi', '上田麗奈 (Reina Ueda)', '김선혜 (Kim Sun-Hye)',
        'The secretary at Yuehai Pavilion. The blood of the qilin, an illuminated beast, flows within her veins.'),
       ('Kamisato Ayaka', 'Frostflake Heron', 'Yashiro Commission', 'Cryo', 'Sword', 5, '28-09', 'Grus Nivis',
        '小N (Xiao N)', 'Erica Mendez', '早見沙織 (Saori Hayami)', '이유리 (Lee Yoo-ri)',
        'Daughter of the Yashiro Commission''s Kamisato Clan. Dignified and elegant, as well as wise and strong.'),
       ('Klee', 'Fleeing Sunlight', 'Knights of Favonius', 'Pyro', 'Catalyst', 5, '27-06', 'Trifolium', '花玲 (Hualing)',
        'Poonam Basu', '久野美咲 (Misaki Kuno)', '방연지 (Bang Yeon-ji)',
        'An explosives expert and a regular at the Knights of Favonius''s confinement room. Also known as Fleeing Sunlight.');

insert into character_material (id, lvl_up1, lvl_up2, lvl_up3_1, lvl_up3_2, lvl_up3_3, tal_up1_1, tal_up1_2, tal_up1_3,
                                tal_up2_1, tal_up2_2, tal_up2_3, tal_up3)
values (1, 87, 152, 37, 38, 39, 109, 110, 111, 37, 38, 39, 133),
       (2, 92, 157, 43, 44, 45, 118, 119, 120, 43, 44, 45, 135),
       (3, 88, 144, 10, 11, 12, 97, 98, 99, 10, 11, 12, 129);

insert into characters (label, title, allegiance, element, weapon, rarity, birthday, astrolab, cn_seiyuu, en_seiyuu,
                        jp_seiyuu, kr_seiyuu, description)
values ();

insert into character_material (id, lvl_up1, lvl_up2, lvl_up3_1, lvl_up3_2, lvl_up3_3, tal_up1_1, tal_up1_2, tal_up1_3,
                                tal_up2_1, tal_up2_2, tal_up2_3, tal_up3)
values ();
